(self.AMP=self.AMP||[]).push({n:"amp-image-lightbox",v:"1496670637476",f:(function(AMP){var g;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function aa(a){return 4>a.length?!1:0==a.lastIndexOf("10.3",0)};Date.now();self.log=self.log||{user:null,dev:null};var n=self.log;function p(){if(n.user)return n.user;throw Error("failed to call initLogConstructor");}function q(){if(n.dev)return n.dev;throw Error("failed to call initLogConstructor");};function r(a,b){a=a.__AMP_TOP||a;return t(a,b)}function ba(a){a=ca(a);a=ca(a);a=a.isSingleDoc()?a.win:a;return t(a,"history")}function ca(a){return a.nodeType?r((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function t(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function da(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ea(a){var b="figure";if(a.closest)return a.closest(b);b=b.toUpperCase();return da(a,function(a){return a.tagName==b})}function fa(a,b){var c=a.getElementsByTagName(b);return c[0]||null};function u(){this.F=null}g=u.prototype;g.add=function(a){var b=this;this.F||(this.F=[]);this.F.push(a);return function(){b.remove(a)}};g.remove=function(a){this.F&&(a=this.F.indexOf(a),-1<a&&this.F.splice(a,1))};g.removeAll=function(){this.F&&(this.F.length=0)};g.fire=function(a){if(this.F)for(var b=this.F,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.F?this.F.length:0};var w,ga="Webkit webkit Moz moz ms O o".split(" ");function ha(a,b,c){var d,e=a.style;w||(w=Object.create(null));var f=w[b];if(!f){f=b;if(void 0===e[b]){var h=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var k=0;k<ga.length;k++){var m=ga[k]+h;if(void 0!==e[m]){h=m;break a}}h=""}void 0!==e[h]&&(f=h)}w[b]=f}(b=f)&&(a.style[b]=d?c+d:c)}function x(a,b){for(var c in b)ha(a,c,b[c])};function y(a){return!!(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)};function z(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c}}function A(a){return z(Number(a.left),Number(a.top),Number(a.width),Number(a.height))};function ia(a){var b=a.getAttribute("srcset");if(b){a=b.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);p().assert(0<a.length,"srcset has to have at least one source: %s",void 0);for(var c=[],d=0;d<a.length;d++){var e=a[d].trim();","==e.substr(-1)&&(e=e.substr(0,e.length-1).trim());var f=e.split(/\s+/,2);if(0!=f.length&&(1!=f.length||f[0])&&(2!=f.length||f[0]||f[1]))if(e=f[0],1==f.length||2==f.length&&!f[1])c.push({url:e,width:void 0,dpr:1});else{var f=f[1].toLowerCase(),
h=f.substring(f.length-1);"w"==h?c.push({url:e,width:parseFloat(f),dpr:void 0}):"x"==h&&c.push({url:e,width:void 0,dpr:parseFloat(f)})}}return new B(c)}var k=p().assert(a.getAttribute("src"),'Either non-empty "srcset" or "src" attribute must be specified: %s',a);return new B([{url:k,width:void 0,dpr:1}])}
function B(a){p().assert(0<a.length,"Srcset must have at least one source");this.C=a;var b=!1,c=!1;for(a=0;a<this.C.length;a++){var d=this.C[a];p().assert((d.width||d.dpr)&&(!d.width||!d.dpr),"Either dpr or width must be specified");b=b||!!d.width;c=c||!!d.dpr}p().assert(!b||!c,"Srcset cannot have both width and dpr sources");b?this.C.sort(ja):this.C.sort(ka);this.kb=b;this.Wa=c}
B.prototype.select=function(a,b){var c=-1;if(this.kb)a:{for(var c=-Infinity,d=this.C.length-1;0<=d;d--){var e=this.C[d].width/b;if(e>=a){c=1.1*(a-c)<e-a&&1.2>=a/c?d+1:d;break a}c=e}c=0}else if(this.Wa){a=-1;c=1E6;for(d=0;d<this.C.length;d++)e=Math.abs((this.C[d].dpr||1)-b),e<c&&(c=e,a=d);c=a}return-1!=c?this.C[c]:this.getLast()};B.prototype.getLast=function(){return this.C[this.C.length-1]};B.prototype.getSources=function(){return this.C};
B.prototype.stringify=function(){for(var a=[],b=0;b<this.C.length;b++){var c=this.C[b];c.width?a.push(c.url+" "+c.width+"w"):c.dpr?a.push(c.url+" "+c.dpr+"x"):a.push(""+c.url)}return a.join(", ")};function ja(a,b){p().assert(a.width!=b.width,"Duplicate width: %s",a.width);return b.width-a.width}function ka(a,b){p().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return b.dpr-a.dpr};function C(a,b,c){var d=this;this.Sa=r(a,"timer");this.Ya=b;this.Va=c||0;this.ba=-1;this.Ba=0;this.P=!1;this.Ta=function(){return d.ka()}}C.prototype.isPending=function(){return-1!=this.ba};C.prototype.schedule=function(a){var b=a||this.Va;this.P&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.Ba?(this.cancel(),this.Ba=c,this.ba=this.Sa.delay(this.Ta,b),!0):!1};C.prototype.ka=function(){this.ba=-1;this.Ba=0;this.P=!0;this.Ya();this.P=!1};
C.prototype.cancel=function(){this.isPending()&&(this.Sa.cancel(this.ba),this.ba=-1)};function D(a,b,c,d){var e=new la(0,0,a,b,c,d,1,1);return e.solveYValueFromXValue.bind(e)}function la(a,b,c,d,e,f,h,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=f;this.x3=h;this.y3=k}g=la.prototype;g.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
g.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,f=0,h=0;8>h;h++){var f=this.getPointX(c),k=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(k)<b)break;else f<a?d=c:e=c,c-=(f-a)/k}for(h=0;Math.abs(f-a)>b&&8>h;h++)f<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),f=this.getPointX(c);return c};
g.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.lerp=function(a,b,c){return a+c*(b-a)};
var ma=D(.25,.1,.25,1),na=D(.42,0,1,1),oa=D(0,0,.58,1),pa=D(.42,0,.58,1),qa={linear:function(a){return a},ease:ma,"ease-in":na,"ease-out":oa,"ease-in-out":pa};function ra(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return D(b[0],b[1],b[2],b[3])}return null}return qa[a]}return a};function sa(){}function E(a,b){this.R=a;this.T=b||r(self,"vsync");this.Na=null;this.A=[]}function ta(a,b,c){var d=ua;return(new E(a)).setCurve(d).add(0,b,1).start(c)}E.prototype.setCurve=function(a){a&&(this.Na=ra(a));return this};E.prototype.add=function(a,b,c,d){this.A.push({delay:a,func:b,duration:c,curve:ra(d)});return this};E.prototype.start=function(a){var b=new va(this.T,this.R,this.A,this.Na,a);b.Ha();return b};
function va(a,b,c,d,e){var f=this;this.T=a;this.R=b;this.A=[];for(b=0;b<c.length;b++){var h=c[b];this.A.push({delay:h.delay,func:h.func,duration:h.duration,curve:h.curve||d,started:!1,completed:!1})}this.Xa=e;this.mb=this.lb=this.M=0;this.P=!1;this.Qa={};this.aa=new Promise(function(a,b){f.Fa=a;f.Ea=b});this.Ra=this.T.createAnimTask(this.R,{mutate:this.gb.bind(this)})}g=va.prototype;g.then=function(a,b){return a||b?this.aa.then(a,b):this.aa};g.thenAlways=function(a){a=a||sa;return this.then(a,a)};
g.halt=function(a){F(this,!1,a||0)};g.Ha=function(){this.M=Date.now();this.P=!0;this.T.canAnimate(this.R)?this.Ra(this.Qa):(q().warn("Animation","cannot animate"),F(this,!1,0))};function F(a,b,c){if(a.P){a.P=!1;if(0!=c){1<a.A.length&&a.A.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(var d=0;d<a.A.length;d++)a.A[d].func(1,!0);else for(d=a.A.length-1;0<=d;d--)a.A[d].func(0,!1)}catch(e){q().error("Animation","completion failed: "+e,e),b=!1}}b?a.Fa():a.Ea()}}
g.gb=function(){if(this.P){for(var a=Date.now(),b=Math.min((a-this.M)/this.Xa,1),c=0;c<this.A.length;c++){var d=this.A[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.A.length;c++)if(d=this.A[c],d.started&&!d.completed)a:{var e,f;if(0<d.duration){if(f=e=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=f)try{f=d.curve(e)}catch(h){q().error("Animation","step curve failed: "+h,h);F(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(h){q().error("Animation","step mutate failed: "+
h,h),F(this,!1,0)}}1==b?F(this,!0,0):this.T.canAnimate(this.R)?this.Ra(this.Qa):(q().warn("Animation","cancel animation"),F(this,!1,0))}};function wa(a){var b;b=void 0===b?" ":b;return function(c,d){for(var e=[],f=0;f<a.length;f++){var h=(0,a[f])(c,d);"string"==typeof h&&e.push(h)}return e.join(b)}}function G(a,b){return function(c,d){for(var e in b)ha(a,e,b[e](c,d))}}function H(a,b){return function(c){return a+(b-a)*c}}function xa(a,b){return function(c){var d=a(c);"number"==typeof d&&(d+="px");if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c+="px");return"translate("+d+","+c+")"}}
function ya(a){return function(b){return"scale("+a(b)+")"}};function za(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function Aa(a,b){this.L=a;this.j=[];this.ea=[];this.I=[];this.i=[];this.h=null;this.eb=b;this.pa=!1;this.ka=new C(a.ownerDocument.defaultView,this.Oa.bind(this));this.Pa=new u;this.Ca=Object.create(null);this.Ma=this.cb.bind(this);this.Ka=this.ab.bind(this);this.La=this.bb.bind(this);this.Ja=this.$a.bind(this);this.L.addEventListener("touchstart",this.Ma);this.L.addEventListener("touchend",this.Ka);this.L.addEventListener("touchmove",this.La);this.L.addEventListener("touchcancel",this.Ja);this.Da=
!1}function Ba(a){var b=a.__AMP_Gestures;b||(b=new Aa(a,!1),a.__AMP_Gestures=b);return b}g=Aa.prototype;g.cleanup=function(){this.L.removeEventListener("touchstart",this.Ma);this.L.removeEventListener("touchend",this.Ka);this.L.removeEventListener("touchmove",this.La);this.L.removeEventListener("touchcancel",this.Ja);delete this.L.__AMP_Gestures;this.ka.cancel()};g.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.Ca[d];e||(this.j.push(c),e=new u,this.Ca[d]=e);return e.add(b)};
g.onPointerDown=function(a){return this.Pa.add(a)};g.cb=function(a){var b=Date.now();this.pa=!1;this.Pa.fire(a);for(var c=0;c<this.j.length;c++)if(!this.I[c]&&(this.i[c]&&this.i[c]<b&&I(this,c),this.j[c].onTouchStart(a))){var d=c;this.ea[d]=!0;this.i[d]=0}J(this,a)};g.bb=function(a){for(var b=Date.now(),c=0;c<this.j.length;c++)this.ea[c]&&(this.i[c]&&this.i[c]<b?I(this,c):this.j[c].onTouchMove(a)||I(this,c));J(this,a)};
g.ab=function(a){for(var b=Date.now(),c=0;c<this.j.length;c++)this.ea[c]&&(this.i[c]&&this.i[c]<b?I(this,c):(this.j[c].onTouchEnd(a),(!this.i[c]||this.i[c]<b)&&I(this,c)));J(this,a)};g.$a=function(a){for(var b=0;b<this.j.length;b++){var c=b;this.I[c]=0;I(this,c)}J(this,a)};function J(a,b){var c=!!a.h||a.pa;a.pa=!1;if(!c)for(var d=Date.now(),e=0;e<a.j.length;e++)if(a.I[e]||a.i[e]&&a.i[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.eb||b.preventDefault());a.Da&&(a.Da=!1,a.Oa())}
g.Oa=function(){for(var a=Date.now(),b=-1,c=0;c<this.j.length;c++)if(!this.I[c])this.i[c]&&this.i[c]<a&&I(this,c);else if(-1==b||this.I[c]>this.I[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.j.length;c++)!this.I[c]&&this.ea[c]&&(d=Math.max(d,this.i[c]-a));if(2>d){for(var a=b,c=this.j[a],e=0;e<this.j.length;e++)if(e!=a){var f=e;this.I[f]=0;I(this,f)}this.I[a]=0;this.i[a]=0;this.h=c;c.acceptStart()}else this.ka.schedule(d)}};function I(a,b){a.ea[b]=!1;a.i[b]=0;a.I[b]||a.j[b].acceptCancel()}
function K(a,b){this.jb=a;this.ha=b}g=K.prototype;g.getType=function(){return this.jb};g.signalReady=function(a){var b=this.ha;if(b.h)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.j.length;d++)b.j[d]==this&&(b.I[d]=c+a,b.i[d]=0);b.Da=!0}};g.signalPending=function(a){var b=this.ha;if(b.h)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.j.length;d++)b.j[d]==this&&(b.i[d]=c+a)};g.signalEnd=function(){var a=this.ha;a.h==this&&(a.h=null,a.pa=!0)};
g.signalEmit=function(a,b){var c=this.ha.Ca[this.getType()];c&&c.fire(new za(this.getType(),a,Date.now(),b))};g.acceptStart=function(){};g.acceptCancel=function(){};g.onTouchStart=function(){return!1};g.onTouchMove=function(){return!1};g.onTouchEnd=function(){};function Ca(){}var Da=Math.round(-16.67/Math.log(.95));function L(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)}function Ea(a,b,c,d,e,f){return(new Fa(a,b,c,d,e,f,void 0)).Ha()}function Fa(a,b,c,d,e,f,h){var k=this;this.T=h||r(self,"vsync");this.R=a;this.qa=f;this.a=b;this.b=c;this.ua=d;this.va=e;this.o=this.m=0;this.v=this.M=Date.now();this.aa=new Promise(function(a,b){k.Fa=a;k.Ea=b});this.Z=!1}g=Fa.prototype;
g.Ha=function(){this.Z=!0;if(.02>=Math.abs(this.ua)&&.02>=Math.abs(this.va))this.qa(this.a,this.b),this.ra(!0);else{this.m=this.ua;this.o=this.va;var a=this.fb.bind(this),b=this.ra.bind(this,!0);this.T.runAnimMutateSeries(this.R,a,5E3).then(b,b)}return this};g.halt=function(){this.Z&&this.ra(!1)};g.then=function(a,b){return a||b?this.aa.then(a,b):this.aa};g.thenAlways=function(a){a=a||Ca;return this.then(a,a)};
g.fb=function(a,b){if(!this.Z)return!1;this.v=Date.now();this.a+=b*this.m;this.b+=b*this.o;if(!this.qa(this.a,this.b))return!1;var c=Math.exp(-a/Da);this.m=this.ua*c;this.o=this.va*c;return.02<Math.abs(this.m)||.02<Math.abs(this.o)};g.ra=function(a){this.Z&&(this.Z=!1,this.v=Date.now(),this.qa(this.a,this.b),a?this.Fa():this.Ea())};function M(a){K.call(this,"tap",a);this.b=this.a=this.f=this.g=0}l(M,K);M.prototype.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};M.prototype.onTouchMove=function(a){return(a=a.changedTouches||a.touches)&&1==a.length&&(this.a=a[0].clientX,this.b=a[0].clientY,a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a)?!1:!0};M.prototype.onTouchEnd=function(){this.signalReady(0)};
M.prototype.acceptStart=function(){this.signalEmit({clientX:this.a,clientY:this.b},null);this.signalEnd()};function N(a){K.call(this,"doubletap",a);this.J=this.b=this.a=this.f=this.g=0}l(N,K);g=N.prototype;g.onTouchStart=function(a){if(1<this.J)return!1;a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){return(a=a.changedTouches||a.touches)&&1==a.length&&(this.a=a[0].clientX,this.b=a[0].clientY,a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a)?(this.acceptCancel(),!1):!0};g.onTouchEnd=function(){this.J++;2>this.J?this.signalPending(300):this.signalReady(0)};g.acceptStart=function(){this.J=0;this.signalEmit({clientX:this.a,clientY:this.b},null);this.signalEnd()};g.acceptCancel=function(){this.J=0};
function O(a,b,c,d){K.call(this,a,b);this.fa=c;this.na=d;this.h=!1;this.o=this.m=this.O=this.v=this.M=this.W=this.V=this.b=this.a=this.f=this.g=0}l(O,K);g=O.prototype;g.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.M=Date.now();this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.a=c;this.b=b;if(this.h)this.S(!1,!1,a);else if(a=Math.abs(c-this.g),c=Math.abs(b-this.f),this.fa&&this.na)(8<=a||8<=c)&&this.signalReady(-10);else if(this.fa)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.na)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1}return!0};g.onTouchEnd=function(a){this.sa(a)};
g.acceptStart=function(){this.h=!0;this.V=this.g;this.W=this.f;this.O=this.M;this.g=this.a;this.f=this.b;this.S(!0,!1,null)};g.acceptCancel=function(){this.h=!1};
g.S=function(a,b,c){this.v=Date.now();var d=this.v-this.O;if(!b&&4<d||b&&16<d)this.m=L(this.a-this.V,d,this.m),this.o=L(this.b-this.W,d,this.o),this.m=1E-4<Math.abs(this.m)?this.m:0,this.o=1E-4<Math.abs(this.o)?this.o:0,this.V=this.a,this.W=this.b,this.O=this.v;this.signalEmit({first:a,last:b,time:this.v,deltaX:this.fa?this.a-this.g:0,deltaY:this.na?this.b-this.f:0,velocityX:this.fa?this.m:0,velocityY:this.na?this.o:0},c)};g.sa=function(a){this.h&&(this.h=!1,this.S(!1,!0,a),this.signalEnd())};
function P(a){O.call(this,"swipe-xy",a,!0,!0)}l(P,O);function Q(a){K.call(this,"tapzoom",a);this.h=!1;this.o=this.m=this.O=this.v=this.M=this.W=this.V=this.J=this.ib=this.hb=this.b=this.a=this.f=this.g=0}l(Q,K);g=Q.prototype;g.onTouchStart=function(a){if(this.h)return!1;a=a.touches;if(!a||1!=a.length)return!1;this.g=a[0].clientX;this.f=a[0].clientY;return!0};
g.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length)if(this.a=b[0].clientX,this.b=b[0].clientY,this.h)this.S(!1,!1,a);else if(a=8<=Math.abs(this.b-this.f),8<=Math.abs(this.a-this.g)||a){if(0==this.J)return this.acceptCancel(),!1;this.signalReady(0)}return!0};g.onTouchEnd=function(a){this.h?this.sa(a):(this.J++,1==this.J?(this.signalPending(400),this.hb=this.a,this.ib=this.b):this.acceptCancel())};g.acceptStart=function(){this.J=0;this.h=!0;this.S(!0,!1,null)};
g.acceptCancel=function(){this.J=0;this.h=!1};g.S=function(a,b,c){this.v=Date.now();a?(this.M=this.v,this.m=this.o=0):2<this.v-this.O&&(this.m=L(this.a-this.V,this.v-this.O,this.m),this.o=L(this.b-this.W,this.v-this.O,this.o));this.V=this.a;this.W=this.b;this.O=this.v;this.signalEmit({first:a,last:b,centerClientX:this.g,centerClientY:this.f,deltaX:this.a-this.g,deltaY:this.b-this.f,velocityX:this.m,velocityY:this.o},c)};g.sa=function(a){this.h&&(this.h=!1,this.S(!1,!0,a),this.signalEnd())};var Ga={"amp-img":!0,"amp-anim":!0},R=D(.4,0,.2,1),S=D(.4,0,.2,1),ua=D(.4,0,.2,1.4);
function Ha(a,b,c){this.ga=a;this.win=b;this.Za=c;this.oa=a.element.ownerDocument.createElement("div");this.oa.classList.add("i-amphtml-image-lightbox-viewer");this.l=a.element.ownerDocument.createElement("img");this.l.classList.add("i-amphtml-image-lightbox-viewer-image");this.oa.appendChild(this.l);this.la=null;this.U={alt:null,"aria-label":null,"aria-labelledby":null};this.ca=this.X=0;this.s=z(0,0,0,0);this.G=z(0,0,0,0);this.ya=this.ja=this.da=this.c=1;this.ia=2;this.xa=this.wa=this.Aa=this.za=
this.u=this.w=this.f=this.g=0;this.N=null;Ia(this)}g=Ha.prototype;g.getElement=function(){return this.oa};g.getImage=function(){return this.l};g.getViewerBox=function(){return this.s};g.getImageBox=function(){return this.G};g.getImageBoxWithOffset=function(){var a;if(0==this.w&&0==this.u)a=this.G;else{a=this.G;var b=this.w,c=this.u;a=0==b&&0==c||0==a.width&&0==a.height?a:z(a.left+b,a.top+c,a.width,a.height)}return a};
g.reset=function(){var a=this;this.l.setAttribute("src","");Object.keys(this.U).forEach(function(b){a.l.removeAttribute(b);a.U[b]=null});this.l.removeAttribute("aria-describedby");this.la=null;this.G=z(0,0,0,0);this.ca=this.X=0;this.da=this.c=this.ja=1;this.ia=2;this.xa=this.wa=this.Aa=this.za=this.u=this.w=this.f=this.g=0;this.N&&this.N.halt();this.N=null};
g.init=function(a,b){var c=this;this.X=a.offsetWidth;this.ca=a.offsetHeight;this.la=ia(a);Object.keys(this.U).forEach(function(b){c.U[b]=a.getAttribute(b);c.U[b]&&c.l.setAttribute(b,c.U[b])});b&&y(b)&&b.src&&this.l.setAttribute("src",b.src)};
g.measure=function(){this.s=A(this.oa.getBoundingClientRect());var a=Math.min(this.s.width/this.X,this.s.height/this.ca),b=Math.min(this.X*a,this.s.width),c=Math.min(this.ca*a,this.s.height);16>=b-this.X&&(b=this.X,c=this.ca);this.G=z(Math.round((this.s.width-b)/2),Math.round((this.s.height-c)/2),Math.round(b),Math.round(c));x(this.l,{top:this.G.top+"px",left:this.G.left+"px",width:this.G.width+"px",height:this.G.height+"px"});this.da=this.c=1;this.f=this.u=this.g=this.w=0;T(this,this.c);U(this);
return Ja(this)};function Ja(a){if(!a.la)return Promise.resolve();a.ja=Math.max(a.ja,a.c);var b=a.la.select(a.G.width*a.ja,a.ga.getDpr()).url;return b==a.l.getAttribute("src")?Promise.resolve():r(a.win,"timer").promise(1).then(function(){a.l.setAttribute("src",b);return a.Za(a.l)})}
function Ia(a){var b=Ba(a.l);b.onGesture(M,function(){a.ga.toggleViewMode()});b.onGesture(P,function(b){var c=b.data.deltaY,e=V(a,a.g+b.data.deltaX,!0),c=W(a,a.f+c,!0);X(a,a.c,e,c,!1);b.data.last&&Ka(a,b.data.velocityX,b.data.velocityY)});b.onPointerDown(function(){a.N&&a.N.halt()});b.onGesture(N,function(b){var c;c=1==a.c?a.ia:a.ya;La(a,c,a.s.width/2-b.data.clientX,a.s.height/2-b.data.clientY,!0).then(function(){return Ma(a,0,0,0,0,0,0)})});b.onGesture(Q,function(b){Na(a,b.data.centerClientX,b.data.centerClientY,
b.data.deltaX,b.data.deltaY);b.data.last&&Ma(a,b.data.centerClientX,b.data.centerClientY,b.data.deltaX,b.data.deltaY,b.data.velocityY,b.data.velocityY)})}function Y(a,b,c,d){return Math.max(b-d,Math.min(c+d,a))}function V(a,b,c){return Y(b,a.za,a.wa,c&&1<a.c?.25*a.s.width:0)}function W(a,b,c){return Y(b,a.Aa,a.xa,c?.25*a.s.height:0)}
function T(a,b){var c=0,d=0,e=a.s.height-a.G.height*b;0<=e?d=c=0:(d=e/2,c=-d);var f=0,h=0;b=a.s.width-a.G.width*b;0<=b?h=f=0:(h=b/2,f=-h);a.za=h;a.Aa=d;a.wa=f;a.xa=c}function U(a){var b=a.l,c;c=a.w;var d=a.u;"number"==typeof c&&(c+="px");void 0===d?c="translate("+c+")":("number"==typeof d&&(d+="px"),c="translate("+c+","+d+")");x(b,{transform:c+" "+("scale("+a.c+")")});1!=a.c&&a.ga.toggleViewMode(!0)}
function Ka(a,b,c){var d=a.u-a.f;1==a.c&&10<Math.abs(d)?a.ga.close():(a.N=Ea(a.l,a.w,a.u,b,c,function(b,c){b=V(a,b,!0);c=W(a,c,!0);if(1>Math.abs(b-a.w)&&1>Math.abs(c-a.u))return!1;X(a,a.c,b,c,!1);return!0}),a.N.thenAlways(function(){a.N=null;return Oa(a)}))}function Na(a,b,c,d,e){var f=Math.sqrt(d*d+e*e),h=Math.abs(e)>Math.abs(d)?Math.sign(e):Math.sign(-d);if(0!=h){var k=a.da*(1+h*f/100),m=a.s.width/2-b,v=a.s.height/2-c;d=Math.min(m,f/100*m);e=Math.min(v,f/100*v);La(a,k,d,e,!1)}}
function La(a,b,c,d,e){b=Y(b,a.ya,a.ia,.25);if(b!=a.c)return T(a,b),c=V(a,a.g+c*b,!1),d=W(a,a.f+d*b,!1),X(a,b,c,d,e)}function Ma(a,b,c,d,e,f,h){d=0==f&&0==h?Promise.resolve():Ea(a.l,d,e,f,h,function(d,e){Na(a,b,c,d,e);return!0}).thenAlways();var k=a.c>a.da;return d.then(function(){return Oa(a)}).then(function(){k&&Ja(a)})}
function X(a,b,c,d,e){var f=b-a.c,h=c-a.w,k=d-a.u,h=Math.sqrt(h*h+k*k),m=0;if(e)var v=250,m=Math.min(v,Math.max(v*h*.01,v*Math.abs(f)));if(16<m&&e){var Qa=H(a.c,b),Ra=H(a.w,c),Sa=H(a.u,d);e=ta(a.l,function(b){a.c=Qa(b);a.w=Ra(b);a.u=Sa(b);U(a)},m).thenAlways(function(){a.c=b;a.w=c;a.u=d;U(a)})}else a.c=b,a.w=c,a.u=d,U(a),e=e?Promise.resolve():void 0;return e}
function Oa(a){var b=Y(a.c,a.ya,a.ia,0);b!=a.c&&T(a,b);var c=V(a,a.w/a.c*b,!1),d=W(a,a.u/a.c*b,!1);return X(a,b,c,d,!0).then(function(){a.da=a.c;a.g=a.w;a.f=a.u})}function Z(a){AMP.BaseElement.call(this,a);this.ta=-1;this.$=this.Y=!1;this.K=this.H=this.D=this.ma=this.B=this.Ga=null;this.Ia=this.Ua.bind(this)}l(Z,AMP.BaseElement);g=Z.prototype;g.isLayoutSupported=function(a){return"nodisplay"==a};
function Pa(a){if(!a.D){a.D=a.element.ownerDocument.createElement("div");a.D.classList.add("i-amphtml-image-lightbox-container");a.element.appendChild(a.D);a.H=new Ha(a,a.win,a.loadPromise.bind(a));a.D.appendChild(a.H.getElement());a.K=a.element.ownerDocument.createElement("div");a.K.setAttribute("id",a.element.getAttribute("id")+"-caption");a.K.classList.add("amp-image-lightbox-caption");a.K.classList.add("i-amphtml-image-lightbox-caption");a.D.appendChild(a.K);var b=a.element.ownerDocument.createElement("button");
b.textContent="Close the lightbox";b.classList.add("i-amphtml-screen-reader");b.tabIndex=-1;b.addEventListener("click",function(){a.close()});a.element.appendChild(b);var c=Ba(a.element);a.element.addEventListener("click",function(b){a.$||a.H.getImage().contains(b.target)||a.close()});c.onGesture(M,function(){a.$||a.close()});c.onGesture(P,function(){})}}
g.activate=function(a){var b=this;if(!this.Y){Pa(this);var c=a.source;p().assert(c&&Ga[c.tagName.toLowerCase()],"Unsupported element: %s",c.tagName);this.Y=!0;Ta(this);Ua(this,c);this.win.document.documentElement.addEventListener("keydown",this.Ia);this.getViewport().enterLightboxMode();Va(this);this.ma=this.getViewport().onChanged(function(){b.Y&&(aa(r(b.win,"platform").getIosVersionString())?r(b.win,"timer").delay(function(){b.H.measure()},500):b.H.measure())});ba(this.getAmpDoc()).push(this.close.bind(this)).then(function(a){b.ta=
a})}};g.Ua=function(a){27==a.keyCode&&this.close()};g.close=function(){this.Y&&(this.$=this.Y=!1,Wa(this),this.ma&&(this.ma(),this.ma=null),this.getViewport().leaveLightboxMode(),-1!=this.ta&&ba(this.getAmpDoc()).pop(this.ta),this.win.document.documentElement.removeEventListener("keydown",this.Ia))};g.toggleViewMode=function(a){void 0!==a?this.D.classList.toggle("i-amphtml-image-lightbox-view-mode",a):this.D.classList.toggle("i-amphtml-image-lightbox-view-mode")};
function Ua(a,b){a.Ga=b;a.B=fa(b,"img");a.H.init(a.Ga,a.B);var c=null;if(!c){var d=ea(b);d&&(c=fa(d,"figcaption"))}if(!c)var e=b.getAttribute("aria-describedby"),c=a.element.ownerDocument.getElementById(e);if(c){var f=c;b=a.K;for(var h=b.ownerDocument.createDocumentFragment(),f=f.firstChild;f;f=f.nextSibling)h.appendChild(f.cloneNode(!0));b.appendChild(h);a.H.getImage().setAttribute("aria-describedby",a.K.getAttribute("id"))}a.K.classList.toggle("i-amphtml-empty",!c)}
function Ta(a){a.H.reset();for(var b=a.K;b.firstChild;)b.removeChild(b.firstChild);a.Ga=null;a.B=null;a.toggleViewMode(!1)}
function Va(a){a.$=!0;x(a.element,{opacity:0,display:""});a.H.measure();var b=new E(a.element);b.add(0,G(a.element,{opacity:H(0,1)}),.6,R);var c=null;if(a.B&&y(a.B)&&a.B.src){c=a.element.ownerDocument.createElement("div");c.classList.add("i-amphtml-image-lightbox-trans");a.element.ownerDocument.body.appendChild(c);var d=A(a.B.getBoundingClientRect()),e=a.H.getImageBox(),f=a.B.cloneNode(!0);f.className="";x(f,{position:"absolute",top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+"px",
transformOrigin:"top left",willChange:"transform"});c.appendChild(f);a.B.classList.add("i-amphtml-ghost");var h=e.top-d.top,k=0!=d.width?e.width/d.width:1,m=Math.max(.2,Math.min(.8,Math.abs(h)/250*.8));b.add(0,G(f,{transform:wa([xa(H(0,e.left-d.left),H(0,h)),ya(H(1,k))])}),m,R);x(a.D,{opacity:0});b.add(.8,G(a.D,{opacity:H(0,1)}),.1,R);b.add(.9,G(c,{opacity:H(1,.01)}),.1,S)}b.start(500).thenAlways(function(){a.$=!1;x(a.element,{opacity:""});x(a.D,{opacity:""});c&&a.element.ownerDocument.body.removeChild(c)})}
function Wa(a){var b=a.H.getImage(),c=a.H.getImageBoxWithOffset(),d=new E(a.element),e=500;d.add(0,G(a.element,{opacity:H(1,0)}),.9,S);var f=null;if(y(b)&&b.src&&a.B){f=a.element.ownerDocument.createElement("div");f.classList.add("i-amphtml-image-lightbox-trans");a.element.ownerDocument.body.appendChild(f);var h=A(a.B.getBoundingClientRect()),k=b.cloneNode(!0);x(k,{position:"absolute",top:c.top+"px",left:c.left+"px",width:c.width+"px",height:c.height+"px",transform:"",transformOrigin:"top left",willChange:"transform"});
f.appendChild(k);d.add(0,G(a.D,{opacity:H(1,0)}),.1,S);var b=h.top-c.top,m=0!=c.width?h.width/c.width:1,v=G(k,{transform:wa([xa(H(0,h.left-c.left),H(0,b)),ya(H(1,m))])}),c=Math.max(.2,Math.min(.8,Math.abs(b)/250*.8));d.add(Math.min(.8-c,.2),function(b,c){v(b);c&&a.B.classList.remove("i-amphtml-ghost")},c,S);d.add(.8,G(f,{opacity:H(1,.01)}),.2,S);e=Math.max(Math.min(Math.abs(b)/250*e,e),300)}d.start(e).thenAlways(function(){a.B&&a.B.classList.remove("i-amphtml-ghost");a.collapse();x(a.element,{opacity:""});
x(a.D,{opacity:""});f&&a.element.ownerDocument.body.removeChild(f);Ta(a)})}AMP.registerElement("amp-image-lightbox",Z,"amp-image-lightbox{position:fixed!important;z-index:1000!important;top:0!important;left:0!important;bottom:0!important;right:0!important;margin:0!important;padding:0!important;overflow:hidden!important;-webkit-transform:translateZ(0)!important;transform:translateZ(0)!important;-ms-touch-action:none!important;touch-action:none!important;background:rgba(0,0,0,.95);color:#f2f2f2}.i-amphtml-image-lightbox-container{position:absolute;z-index:0;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.i-amphtml-image-lightbox-trans{pointer-events:none!important;position:fixed;z-index:1001;top:0;left:0;bottom:0;right:0}.i-amphtml-image-lightbox-caption{position:absolute!important;z-index:2!important;bottom:0!important;left:0!important;right:0!important}.i-amphtml-image-lightbox-caption.i-amphtml-empty,.i-amphtml-image-lightbox-view-mode .i-amphtml-image-lightbox-caption{visibility:hidden}.amp-image-lightbox-caption{background:rgba(0,0,0,.5);max-height:25%;padding:8px}.i-amphtml-image-lightbox-viewer{position:absolute;z-index:1;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.i-amphtml-image-lightbox-viewer-image{position:absolute;z-index:1;display:block;-webkit-transform-origin:50% 50%;transform-origin:50% 50%}\n/*# sourceURL=/extensions/amp-image-lightbox/0.1/amp-image-lightbox.css*/");
})});
//# sourceMappingURL=amp-image-lightbox-0.1.js.map
