(self.AMP=self.AMP||[]).push({n:"amp-mustache",v:"1496670637476",f:(function(AMP){function ea(b,a){function c(){}c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b;for(var f in a)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(a,f);d&&Object.defineProperty(b,f,d)}else b[f]=a[f]}function v(b,a){return a.length>b.length?!1:0==b.lastIndexOf(a,0)};var fa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;Date.now();self.log=self.log||{user:null,dev:null};var ga=self.log;function F(){if(ga.user)return ga.user;throw Error("failed to call initLogConstructor");};var K=self.AMP_CONFIG||{},ha=K.cdnUrl||"https://cdn.ampproject.org",ia=("string"==typeof K.cdnProxyRegex?new RegExp(K.cdnProxyRegex):K.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var ja,ka,oa=/[?&]amp_js[^&]*/;
function N(b){var a;ja||(ja=self.document.createElement("a"),ka=self.UrlCache||(self.UrlCache=Object.create(null)));var c=ka[b];if(c)return c;var f=ja;f.href=b;f.protocol||(f.href=f.href);var d={href:f.href,protocol:f.protocol,host:f.host,hostname:f.hostname,port:"0"==f.port?"":f.port,pathname:f.pathname,search:f.search,hash:f.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
f.origin&&"null"!=f.origin?f.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;var p=d,k=p;return a?k:ka[b]=k}function pa(b){"string"==typeof b&&(b=N(b));return ia.test(b.origin)}
function wa(b,a){"string"==typeof a&&(a=N(a));var c;if("function"==typeof URL)c=(new URL(b,a.href)).toString();else{c=b;var f=a;"string"==typeof f&&(f=N(f));c=c.replace(/\\/g,"/");var d=N(c);c=v(c.toLowerCase(),d.protocol)?d.href:v(c,"//")?f.protocol+c:v(c,"/")?f.origin+c:f.origin+f.pathname.replace(/\/[^/]*$/,"/")+c}return c};function S(b){F().assert(0<b.length,"Srcset must have at least one source");this.f=b;var a=!1,c=!1;for(b=0;b<this.f.length;b++){var f=this.f[b];F().assert((f.width||f.dpr)&&(!f.width||!f.dpr),"Either dpr or width must be specified");a=a||!!f.width;c=c||!!f.dpr}F().assert(!a||!c,"Srcset cannot have both width and dpr sources");a?this.f.sort(xa):this.f.sort(ya);this.C=a;this.B=c}
S.prototype.select=function(b,a){var c=-1;if(this.C)a:{for(var c=-Infinity,f=this.f.length-1;0<=f;f--){var d=this.f[f].width/a;if(d>=b){c=1.1*(b-c)<d-b&&1.2>=b/c?f+1:f;break a}c=d}c=0}else if(this.B){b=-1;c=1E6;for(f=0;f<this.f.length;f++)d=Math.abs((this.f[f].dpr||1)-a),d<c&&(c=d,b=f);c=b}return-1!=c?this.f[c]:this.getLast()};S.prototype.getLast=function(){return this.f[this.f.length-1]};S.prototype.getSources=function(){return this.f};
S.prototype.stringify=function(){for(var b=[],a=0;a<this.f.length;a++){var c=this.f[a];c.width?b.push(c.url+" "+c.width+"w"):c.dpr?b.push(c.url+" "+c.dpr+"x"):b.push(""+c.url)}return b.join(", ")};function xa(b,a){F().assert(b.width!=a.width,"Duplicate width: %s",b.width);return a.width-b.width}function ya(b,a){F().assert(b.dpr!=a.dpr,"Duplicate dpr: %s",b.dpr);return a.dpr-b.dpr};var za=function(){function b(r){var b=(""+r).match(x);return b?new g(h(b[1]),h(b[2]),h(b[3]),h(b[4]),h(b[5]),h(b[6]),h(b[7])):null}function a(b,a,z,e,h,k,u){b=new g(f(b,t),f(a,t),c(z),0<e?e.toString():null,f(h,B),null,c(u));k&&("string"===typeof k?b.setRawQuery(k.replace(/[^?&=0-9A-Za-z_\-~.%]/g,d)):b.setAllParameters(k));return b}function c(b){return"string"==typeof b?encodeURIComponent(b):null}function f(b,a){return"string"==typeof b?encodeURI(b).replace(a,d):null}function d(b){var r=b.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(r>>4&15)+"0123456789ABCDEF".charAt(r&15)}function p(b){return b.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function k(b){if(null===b)return null;b=p(b);for(var r=E,a;(a=b.replace(r,"$1"))!=b;b=a);return b}function e(b,a){var r=b.clone(),c=a.hasScheme();c?r.setRawScheme(a.getRawScheme()):c=a.hasCredentials();c?r.setRawCredentials(a.getRawCredentials()):c=a.hasDomain();c?r.setRawDomain(a.getRawDomain()):c=a.hasPort();var g=a.getRawPath(),d=k(g);if(c)r.setPort(a.getPort()),
d=d&&d.replace(u,"");else if(c=!!g){if(47!==d.charCodeAt(0))var f=k(r.getRawPath()||"").replace(u,""),e=f.lastIndexOf("/")+1,d=k((e?f.substring(0,e):"")+k(g)).replace(u,"")}else d=d&&d.replace(u,""),d!==g&&r.setRawPath(d);c?r.setRawPath(d):c=a.hasQuery();c?r.setRawQuery(a.getRawQuery()):c=a.hasFragment();c&&r.setRawFragment(a.getRawFragment());return r}function g(b,a,c,d,g,f,e){this.o=b;this.j=a;this.l=c;this.v=d;this.h=g;this.g=f;this.m=e;this.c=null}function h(b){return"string"==typeof b&&0<b.length?
b:null}var C=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,E=new RegExp(C),u=/^(?:\.\.\/)*(?:\.\.$)?/;g.prototype.toString=function(){var b=[];null!==this.o&&b.push(this.o,":");null!==this.l&&(b.push("//"),null!==this.j&&b.push(this.j,"@"),b.push(this.l),null!==this.v&&b.push(":",this.v.toString()));null!==this.h&&b.push(this.h);null!==this.g&&b.push("?",this.g);null!==this.m&&b.push("#",this.m);return b.join("")};g.prototype.clone=function(){return new g(this.o,this.j,this.l,
this.v,this.h,this.g,this.m)};g.prototype.getScheme=function(){return this.o&&decodeURIComponent(this.o).toLowerCase()};g.prototype.getRawScheme=function(){return this.o};g.prototype.setScheme=function(b){this.o=f(b,t);return this};g.prototype.setRawScheme=function(b){this.o=b?b:null;return this};g.prototype.hasScheme=function(){return null!==this.o};g.prototype.getCredentials=function(){return this.j&&decodeURIComponent(this.j)};g.prototype.getRawCredentials=function(){return this.j};g.prototype.setCredentials=
function(b){this.j=f(b,t);return this};g.prototype.setRawCredentials=function(b){this.j=b?b:null;return this};g.prototype.hasCredentials=function(){return null!==this.j};g.prototype.getDomain=function(){return this.l&&decodeURIComponent(this.l)};g.prototype.getRawDomain=function(){return this.l};g.prototype.setDomain=function(b){return this.setRawDomain(b&&encodeURIComponent(b))};g.prototype.setRawDomain=function(b){this.l=b?b:null;return this.setRawPath(this.h)};g.prototype.hasDomain=function(){return null!==
this.l};g.prototype.getPort=function(){return this.v&&decodeURIComponent(this.v)};g.prototype.setPort=function(b){if(b){b=Number(b);if(b!==(b&65535))throw Error("Bad port number "+b);this.v=""+b}else this.v=null;return this};g.prototype.hasPort=function(){return null!==this.v};g.prototype.getPath=function(){return this.h&&decodeURIComponent(this.h)};g.prototype.getRawPath=function(){return this.h};g.prototype.setPath=function(b){return this.setRawPath(f(b,B))};g.prototype.setRawPath=function(b){b?
(b=String(b),this.h=!this.l||/^\//.test(b)?b:"/"+b):this.h=null;return this};g.prototype.hasPath=function(){return null!==this.h};g.prototype.getQuery=function(){return this.g&&decodeURIComponent(this.g).replace(/\+/g," ")};g.prototype.getRawQuery=function(){return this.g};g.prototype.setQuery=function(b){this.c=null;this.g=c(b);return this};g.prototype.setRawQuery=function(b){this.c=null;this.g=b?b:null;return this};g.prototype.hasQuery=function(){return null!==this.g};g.prototype.setAllParameters=
function(b){if("object"===typeof b&&!(b instanceof Array)&&(b instanceof Object||"[object Array]"!==Object.prototype.toString.call(b))){var a=[],c=-1,d;for(d in b){var g=b[d];"string"===typeof g&&(a[++c]=d,a[++c]=g)}b=a}this.c=null;for(var f=[],r="",e=0;e<b.length;)d=b[e++],g=b[e++],f.push(r,encodeURIComponent(d.toString())),r="&",g&&f.push("=",encodeURIComponent(g.toString()));this.g=f.join("");return this};g.prototype.w=function(){if(!this.c){var b=this.g;if(b){for(var a=b.split(/[&\?]/),b=[],c=
-1,d=0;d<a.length;++d){var g=a[d].match(/^([^=]*)(?:=(.*))?$/);b[++c]=decodeURIComponent(g[1]).replace(/\+/g," ");b[++c]=decodeURIComponent(g[2]||"").replace(/\+/g," ")}this.c=b}else this.c=[]}};g.prototype.setParameterValues=function(b,a){"string"===typeof a&&(a=[a]);this.w();for(var c=0,d=this.c,g=[],f=0;f<d.length;f+=2)b===d[f]?c<a.length&&g.push(b,a[c++]):g.push(d[f],d[f+1]);for(;c<a.length;)g.push(b,a[c++]);this.setAllParameters(g);return this};g.prototype.removeParameter=function(b){return this.setParameterValues(b,
[])};g.prototype.getAllParameters=function(){this.w();return this.c.slice(0,this.c.length)};g.prototype.getParameterValues=function(b){this.w();for(var a=[],c=0;c<this.c.length;c+=2)b===this.c[c]&&a.push(this.c[c+1]);return a};g.prototype.getParameterMap=function(){this.w();for(var b={},a=0;a<this.c.length;a+=2){var c=this.c[a++],d=this.c[a++];c in b?b[c].push(d):b[c]=[d]}return b};g.prototype.getParameterValue=function(b){this.w();for(var a=0;a<this.c.length;a+=2)if(b===this.c[a])return this.c[a+
1];return null};g.prototype.getFragment=function(){return this.m&&decodeURIComponent(this.m)};g.prototype.getRawFragment=function(){return this.m};g.prototype.setFragment=function(b){this.m=b?encodeURIComponent(b):null;return this};g.prototype.setRawFragment=function(b){this.m=b?b:null;return this};g.prototype.hasFragment=function(){return null!==this.m};var x=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,t=/[#\/\?@]/g,B=/[\#\?]/g;g.parse=b;
g.create=a;g.resolve=e;g.collapse_dots=k;g.utils={mimeTypeOf:function(a){var c=b(a);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(a,c){return a?e(b(a),b(c)).toString():""+c}};return g}(),W={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};W.atype=W.atype;
W.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,"textarea::required":0,
"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,"track::label":0,
"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};W.ATTRIBS=W.ATTRIBS;W.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};W.eflags=W.eflags;
W.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};W.ELEMENTS=W.ELEMENTS;
W.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",textarea:"HTMLTextAreaElement",tfoot:"HTMLTableSectionElement",
th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};W.ELEMENT_DOM_INTERFACES=W.ELEMENT_DOM_INTERFACES;W.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};W.ueffects=W.ueffects;
W.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};W.URIEFFECTS=W.URIEFFECTS;W.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};W.ltypes=W.ltypes;
W.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};W.LOADERTYPES=W.LOADERTYPES;
var Aa=function(b){function a(b){if(Z.hasOwnProperty(b))return Z[b];var a=b.match(ra);return a?String.fromCharCode(parseInt(a[1],10)):(a=b.match(sa))?String.fromCharCode(parseInt(a[1],16)):aa&&O.test(b)?(aa.innerHTML="&"+b+";",a=aa.textContent,Z[b]=a):"&"+b+";"}function c(b,c){return a(c)}function f(b){return b.replace(P,"")}function d(b){return b.replace(L,c)}function p(b){return(""+b).replace(l,"&amp;").replace(D,"&lt;").replace(G,"&gt;").replace(Q,"&#34;")}function k(b){return b.replace(q,"&amp;$1").replace(D,
"&lt;").replace(G,"&gt;")}function e(b){var a={cdata:b.cdata||b.cdata,comment:b.comment||b.comment,endDoc:b.endDoc||b.endDoc,endTag:b.endTag||b.endTag,pcdata:b.pcdata||b.pcdata,rcdata:b.rcdata||b.rcdata,startDoc:b.startDoc||b.startDoc,startTag:b.startTag||b.startTag};return function(b,c){var n=a,d=C(b);h(n,d,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function g(b,a,c,d,m){return function(){h(b,a,c,d,m)}}function h(a,c,d,f,m){try{a.startDoc&&0==d&&a.startDoc(m);for(var w,n,M,e=d,H=c.length;e<H;){var k=
c[e++],h=c[e];switch(k){case "&":U.test(h)?(a.pcdata&&a.pcdata("&"+h,m,A,g(a,c,e,f,m)),e++):a.pcdata&&a.pcdata("&amp;",m,A,g(a,c,e,f,m));break;case "</":(w=/^([-\w:]+)[^\'\"]*/.exec(h))?w[0].length===h.length&&">"===c[e+1]?(e+=2,M=w[1].toLowerCase(),a.endTag&&a.endTag(M,m,A,g(a,c,e,f,m))):e=E(c,e,a,m,A,f):a.pcdata&&a.pcdata("&lt;/",m,A,g(a,c,e,f,m));break;case "<":if(w=/^([-\w:]+)\s*\/?/.exec(h))if(w[0].length===h.length&&">"===c[e+1]){e+=2;M=w[1].toLowerCase();a.startTag&&a.startTag(M,[],m,A,g(a,
c,e,f,m));var l=b.ELEMENTS[M];l&ta&&(e=x(c,{name:M,next:e,eflags:l},a,m,A,f))}else e=u(c,e,a,m,A,f);else a.pcdata&&a.pcdata("&lt;",m,A,g(a,c,e,f,m));break;case "\x3c!--":if(!f.noMoreEndComments){for(n=e+1;n<H&&(">"!==c[n]||!/--$/.test(c[n-1]));n++);if(n<H){if(a.comment){var q=c.slice(e,n).join("");a.comment(q.substr(0,q.length-2),m,A,g(a,c,n+1,f,m))}e=n+1}else f.noMoreEndComments=!0}f.noMoreEndComments&&a.pcdata&&a.pcdata("&lt;!--",m,A,g(a,c,e,f,m));break;case "<!":if(/^\w/.test(h)){if(!f.noMoreGT){for(n=
e+1;n<H&&">"!==c[n];n++);n<H?e=n+1:f.noMoreGT=!0}f.noMoreGT&&a.pcdata&&a.pcdata("&lt;!",m,A,g(a,c,e,f,m))}else a.pcdata&&a.pcdata("&lt;!",m,A,g(a,c,e,f,m));break;case "<?":if(!f.noMoreGT){for(n=e+1;n<H&&">"!==c[n];n++);n<H?e=n+1:f.noMoreGT=!0}f.noMoreGT&&a.pcdata&&a.pcdata("&lt;?",m,A,g(a,c,e,f,m));break;case ">":a.pcdata&&a.pcdata("&gt;",m,A,g(a,c,e,f,m));break;case "":break;default:a.pcdata&&a.pcdata(k,m,A,g(a,c,e,f,m))}}a.endDoc&&a.endDoc(m)}catch(ua){if(ua!==A)throw ua;}}function C(b){var a=/(<\/|<\!--|<[!?]|[&<>])/g;
b+="";if(ma)return b.split(a);for(var c=[],d=0,f;null!==(f=a.exec(b));)c.push(b.substring(d,f.index)),c.push(f[0]),d=f.index+f[0].length;c.push(b.substring(d));return c}function E(b,a,c,d,f,e){var m=t(b,a);if(!m)return b.length;c.endTag&&c.endTag(m.name,d,f,g(c,b,a,e,d));return m.next}function u(b,a,c,d,f,e){a=t(b,a);if(!a)return b.length;c.startTag&&c.startTag(a.name,a.attrs,d,f,g(c,b,a.next,e,d));return a.eflags&ta?x(b,a,c,d,f,e):a.next}function x(a,c,d,f,e,h){var m=a.length;na.hasOwnProperty(c.name)||
(na[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var n=na[c.name],M=c.next,w=c.next+1;w<m&&("</"!==a[w-1]||!n.test(a[w]));w++);w<m&&--w;var H=a.slice(M,w).join("");if(c.eflags&b.eflags.CDATA)d.cdata&&d.cdata(H,f,e,g(d,a,w,h,f));else if(c.eflags&b.eflags.RCDATA)d.rcdata&&d.rcdata(k(H),f,e,g(d,a,w,h,f));else throw Error("bug");return w}function t(a,c){var d=/^([-\w:]+)/.exec(a[c]),f={};f.name=d[1].toLowerCase();f.eflags=b.ELEMENTS[f.name];var e=a[c].substr(d[0].length);c+=1;for(var g=a.length;c<
g&&">"!==a[c];c++)e+=a[c];if(!(g<=c)){for(var n=[];""!==e;)if(d=J.exec(e))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var h=d[4]||d[6],w=!1,k=[e,a[c++]];c<g;c++){if(w){if(">"===a[c])break}else 0<=a[c].indexOf(h)&&(w=!0);k.push(a[c])}if(g<=c)break;e=k.join("")}else{var l=d[1].toLowerCase(),q=d[2]?B(d[3]):"";n.push(l,q);e=e.substr(d[0].length)}else e=e.replace(/^[\s\S][^a-z\s]*/,"");f.attrs=n;f.next=c+1;return f}}function B(b){var a=b.charCodeAt(0);if(34===a||39===a)b=b.substr(1,b.length-2);return d(f(b))}function r(a){function c(b,
a){f||a.push(b)}var d,f;return e({startDoc:function(){d=[];f=!1},startTag:function(c,e,g){if(!f&&b.ELEMENTS.hasOwnProperty(c)){var m=b.ELEMENTS[c];if(!(m&b.eflags.FOLDABLE)){var n=a(c,e);if(n){if("object"!==typeof n)throw Error("tagPolicy did not return object (old API?)");if("attribs"in n)e=n.attribs;else throw Error("tagPolicy gave no attribs");var h,k;"tagName"in n?(k=n.tagName,h=b.ELEMENTS[k]):(k=c,h=m);if(m&b.eflags.OPTIONAL_ENDTAG){var w=d[d.length-1];!w||w.orig!==c||w.rep===k&&c===k||g.push("</",
w.rep,">")}m&b.eflags.EMPTY||d.push({orig:c,rep:k});g.push("<",k);for(var l=0,q=e.length;l<q;l+=2){var G=e[l],V=e[l+1];null!==V&&void 0!==V&&g.push(" ",G,'="',p(V),'"')}g.push(">");m&b.eflags.EMPTY&&!(h&b.eflags.EMPTY)&&g.push("</",k,">")}else f=!(m&b.eflags.EMPTY)}}},endTag:function(a,c){if(f)f=!1;else if(b.ELEMENTS.hasOwnProperty(a)){var e=b.ELEMENTS[a];if(!(e&(b.eflags.EMPTY|b.eflags.FOLDABLE))){if(e&b.eflags.OPTIONAL_ENDTAG)for(e=d.length;0<=--e;){var g=d[e].orig;if(g===a)break;if(!(b.ELEMENTS[g]&
b.eflags.OPTIONAL_ENDTAG))return}else for(e=d.length;0<=--e&&d[e].orig!==a;);if(!(0>e)){for(var m=d.length;--m>e;){var n=d[m].rep;b.ELEMENTS[n]&b.eflags.OPTIONAL_ENDTAG||c.push("</",n,">")}e<d.length&&(a=d[e].rep);d.length=e;c.push("</",a,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(b){for(;d.length;d.length--)b.push("</",d[d.length-1].rep,">")}})}function I(b,a,c,d,f){if(!f)return null;try{var e=za.parse(""+b);if(e&&(!e.hasScheme()||Ha.test(e.getScheme()))){var g=f(e,a,c,d);return g?g.toString():
null}}catch(Ta){}return null}function z(b,a,c,d,f){c||b(a+" removed",{change:"removed",tagName:a});if(d!==f){var e="changed";d&&!f?e="removed":!d&&f&&(e="added");b(a+"."+c+" "+e,{change:e,tagName:a,attribName:c,oldValue:d,newValue:f})}}function T(b,a,c){var d;d=a+"::"+c;if(b.hasOwnProperty(d))return b[d];d="*::"+c;if(b.hasOwnProperty(d))return b[d]}function qa(a,c){return T(b.ATTRIBS,a,c)}function la(a,c){return T(b.LOADERTYPES,a,c)}function X(a,c){return T(b.URIEFFECTS,a,c)}function Y(a,c,d,f,e){for(var g=
0;g<c.length;g+=2){var k=c[g],h=c[g+1],l=h,m=null,q;if((q=a+"::"+k,b.ATTRIBS.hasOwnProperty(q))||(q="*::"+k,b.ATTRIBS.hasOwnProperty(q)))m=b.ATTRIBS[q];if(null!==m)switch(m){case b.atype.NONE:break;case b.atype.SCRIPT:h=null;e&&z(e,a,k,l,h);break;case b.atype.STYLE:if("undefined"===typeof ba){h=null;e&&z(e,a,k,l,h);break}var n=[];ba(h,{declaration:function(a,c){var e=a.toLowerCase();ca(e,c,d?function(a){return I(a,b.ueffects.SAME_DOCUMENT,b.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:null);c.length&&
n.push(e+": "+c.join(" "))}});h=0<n.length?n.join(" ; "):null;e&&z(e,a,k,l,h);break;case b.atype.ID:case b.atype.IDREF:case b.atype.IDREFS:case b.atype.GLOBAL_NAME:case b.atype.LOCAL_NAME:case b.atype.CLASSES:h=f?f(h):h;e&&z(e,a,k,l,h);break;case b.atype.URI:h=I(h,X(a,k),la(a,k),{TYPE:"MARKUP",XML_ATTR:k,XML_TAG:a},d);e&&z(e,a,k,l,h);break;case b.atype.URI_FRAGMENT:h&&"#"===h.charAt(0)?(h=h.substring(1),h=f?f(h):h,null!==h&&void 0!==h&&(h="#"+h)):h=null;e&&z(e,a,k,l,h);break;default:h=null,e&&z(e,
a,k,l,h)}else h=null,e&&z(e,a,k,l,h);c[g+1]=h}return c}function da(a,c,d){return function(e,f){if(b.ELEMENTS[e]&b.eflags.UNSAFE)d&&z(d,e,void 0,void 0,void 0);else return{attribs:Y(e,f,a,c,d)}}}function R(b,a){var c=[];r(a)(b,c);return c.join("")}function V(b,a,c,d){a=da(a,c,d);return R(b,a)}var ba,ca,va;"undefined"!==typeof window&&(ba=window.parseCssDeclarations,ca=window.sanitizeCssProperty,va=window.cssSchema);var Z={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},
ra=/^#(\d+)$/,sa=/^#x([0-9A-Fa-f]+)$/,O=/^[A-Za-z][A-za-z0-9]+$/,aa="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,P=/\0/g,L=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,U=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,l=/&/g,q=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,D=/[<]/g,G=/>/g,Q=/\"/g,J=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,ma=3==="a,b".split(/(,)/).length,ta=b.eflags.CDATA|b.eflags.RCDATA,A=
{},na={},Ha=/^(?:https?|mailto)$/i,y={};y.escapeAttrib=y.escapeAttrib=p;y.makeHtmlSanitizer=y.makeHtmlSanitizer=r;y.makeSaxParser=y.makeSaxParser=e;y.makeTagPolicy=y.makeTagPolicy=da;y.normalizeRCData=y.normalizeRCData=k;y.sanitize=y.sanitize=V;y.sanitizeAttribs=y.sanitizeAttribs=Y;y.sanitizeWithPolicy=y.sanitizeWithPolicy=R;y.unescapeEntities=y.unescapeEntities=d;return y}(W);var Ba={applet:!0,audio:!0,base:!0,embed:!0,form:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,script:!0,style:!0,svg:!0,template:!0,video:!0},Ca={br:!0,col:!0,hr:!0,img:!0,input:!0,source:!0,track:!0,wbr:!0,area:!0,base:!0,command:!0,embed:!0,keygen:!0,link:!0,meta:!0,param:!0},Da="b br code del em i ins mark q s small strong sub sup time u".split(" "),Ea=["fallback","href","on","placeholder","text"],Fa=/^data-/i,Ga=["_top","_blank"],Ia=["javascript:","vbscript:","data:","<script",
"\x3c/script"],Ja={input:{type:/(?:image|file|password|button)/i}},Ka="form formaction formmethod formtarget formnovalidate formenctype".split(" "),La={input:Ka,textarea:Ka,select:Ka};
function Ma(b){function a(b){0==d&&f.push(b)}var c=Aa.makeTagPolicy(),f=[],d=0,p=Aa.makeSaxParser({startTag:function(b,e){if(0<d)Ca[b]||d++;else{for(var f=Object.create(null),h=0;h<e.length;h+=2){var k=e[h];k&&"["==k[0]&&"]"==k[k.length-1]&&(f[h]=!0,e[h]=k.slice(1,-1))}if(Ba[b])d++;else if(!v(b,"amp-")){var p=e.slice(0),u=c(b,e);if(u)for(e=u.attribs,h=0;h<e.length;h+=2){var x=e[h];Ea.includes(x)?e[h+1]=p[h+1]:0==x.search(Fa)&&(e[h+1]=p[h+1])}else d++;if("a"==b){for(var h=-1,t=!1,B=0;B<p.length;B+=
2)"target"==p[B]?h=B+1:"href"==p[B]&&(t=null!=e[B+1]);var r=-1!=h?p[h]:null;null!=r?(r=r.toLowerCase(),-1!=Ga.indexOf(r)?e[h]=r:e[h]="_top"):t&&(e.push("target"),e.push("_top"))}}if(0<d)Ca[b]&&d--;else{a("<");a(b);for(h=0;h<e.length;h+=2){var I=e[h],z=e[h+1];Na(b,I,z)&&(a(" "),f[h]?a("["+I+"]"):a(I),a('="'),z&&a(Aa.escapeAttrib(Oa(b,I,z))),a('"'))}a(">")}}},endTag:function(b){0<d?d--:(a("</"),a(b),a(">"))},pcdata:a,rcdata:a,cdata:a});p(b);return f.join("")}
function Na(b,a,c){if(v(a,"on")&&"on"!=a||"style"==a||"class"==a&&c&&/(^|\W)i-amphtml-/i.test(c))return!1;if(c)for(var f=c.toLowerCase().replace(/[\s,\u0000]+/g,""),d=0;d<Ia.length;d++)if(-1!=f.indexOf(Ia[d]))return!1;var p=La[b];if(p&&-1!=p.indexOf(a))return!1;var k=Ja[b];if(k){var e=k[a];if(e&&-1!=c.search(e))return!1}return!0}function Oa(b,a,c){return"src"==a||"href"==a||"srcset"==a?Pa(b,a,c):c}
function Pa(b,a,c){var f=self.location;var d=N(c).search,p=Object.create(null);if(d)for(var k;k=fa.exec(d);){var e=decodeURIComponent(k[1]).trim();k=k[2]?decodeURIComponent(k[2]).trim():"";p[e]=k}F().assert(!("__amp_source_origin"in p),"Source origin is not allowed in %s",c);var g=pa(f);d=f;"string"==typeof d&&(d=N(d));pa(d)?(p=d.pathname.split("/"),e=p[1],F().assert("a"==e||"c"==e||"v"==e,"Unknown path prefix in url %s",d.href),e=p[2],k="s"==e?"https://"+decodeURIComponent(p[3]):"http://"+decodeURIComponent(e),
F().assert(0<k.indexOf("."),"Expected a . in origin %s",k),p.splice(1,"s"==e?3:2),p=k+p.join("/"),e=(e=d.search)&&"?"!=e?(e=e.replace(oa,"").replace(/^[?&]/,""))?"?"+e:"":"",d=p+e+(d.hash||"")):d=d.href;d=N(d);if("href"==a&&!v(c,"#"))return wa(c,d);if("src"==a)return"amp-img"==b?Qa(c,d,g):wa(c,d);if("srcset"==a){var h;try{var C=c.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);F().assert(0<C.length,"srcset has to have at least one source: %s",void 0);b=[];for(a=0;a<
C.length;a++){var E=C[a].trim();","==E.substr(-1)&&(E=E.substr(0,E.length-1).trim());var u=E.split(/\s+/,2);if(0!=u.length&&(1!=u.length||u[0])&&(2!=u.length||u[0]||u[1])){var x=u[0];if(1==u.length||2==u.length&&!u[1])b.push({url:x,width:void 0,dpr:1});else{var t=u[1].toLowerCase(),B=t.substring(t.length-1);"w"==B?b.push({url:x,width:parseFloat(t),dpr:void 0}):"x"==B&&b.push({url:x,width:void 0,dpr:parseFloat(t)})}}}h=new S(b)}catch(r){return F().error("sanitizer","Failed to parse srcset: ",r),c}c=
h.getSources();for(C=0;C<c.length;C++)c[C].url=Qa(c[C].url,d,g);return h.stringify()}return c}function Qa(b,a,c){b=N(wa(b,a));return"data:"==b.protocol||pa(b)||!c?b.href:ha+"/i/"+("https:"==b.protocol?"s/":"")+encodeURIComponent(b.host)+b.pathname+(b.search||"")+(b.hash||"")};var Ra={};
(function defineMustache(a,c){c(Ra)})(this,function mustacheFactory(a){function c(a){return"function"===typeof a}function f(a){return r(a)?"array":typeof a}function d(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function p(a,c){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,c)}function k(a,c){return I.call(a,c)}function e(a){return!k(z,a)}function g(a){return String(a).replace(/[&<>"'`=\/]/g,function ca(a){return T[a]})}function h(c,f){function g(){if(O&&!x)for(;t.length;)delete p[t.pop()];
else t=[];x=O=!1}function h(a){"string"===typeof a&&(a=a.split(la,2));if(!r(a)||2!==a.length)throw Error("Invalid tags: "+a);P=new RegExp(d(a[0])+"\\s*");L=new RegExp("\\s*"+d(a[1]));U=new RegExp("\\s*"+d("}"+a[1]))}if(!c)return[];var k=[],p=[],t=[],O=!1,x=!1,P,L,U;h(f||a.tags);for(var l=new u(c),q,D,G,Q,J;!l.eos();){c=l.pos;if(D=l.scanUntil(P)){q=0;for(var ma=D.length;q<ma;++q)G=D.charAt(q),e(G)?t.push(p.length):x=!0,p.push(["text",G,c,c+1]),c+=1,"\n"===G&&g()}if(!l.scan(P))break;O=!0;q=l.scan(da)||
"name";l.scan(qa);"="===q?(D=l.scanUntil(X),l.scan(X),l.scanUntil(L)):"{"===q?(D=l.scanUntil(U),l.scan(Y),l.scanUntil(L),q="&"):D=l.scanUntil(L);if(!l.scan(L))throw Error("Unclosed tag at "+l.pos);Q=[q,D,c,l.pos];p.push(Q);if("#"===q||"^"===q)k.push(Q);else if("/"===q){J=k.pop();if(!J)throw Error('Unopened section "'+D+'" at '+c);if(J[1]!==D)throw Error('Unclosed section "'+J[1]+'" at '+c);}else if("name"===q||"{"===q||"&"===q)x=!0}if(J=k.pop())throw Error('Unclosed section "'+J[1]+'" at '+l.pos);
return E(C(p))}function C(a){for(var c=[],d,e,f=0,g=a.length;f<g;++f)if(d=a[f])"text"===d[0]&&e&&"text"===e[0]?(e[1]+=d[1],e[3]=d[3]):(c.push(d),e=d);return c}function E(a){for(var c=[],d=c,e=[],f,g,h=0,k=a.length;h<k;++h)switch(f=a[h],f[0]){case "#":case "^":d.push(f);e.push(f);d=f[4]=[];break;case "/":g=e.pop();g[5]=f[2];d=0<e.length?e[e.length-1][4]:c;break;default:d.push(f)}return c}function u(a){this.tail=this.string=a;this.pos=0}function x(a,c){this.view=a;this.cache={".":this.view};this.parent=
c}function t(){this.cache={}}var B=Object.prototype.toString,r=Array.isArray||function ba(a){return"[object Array]"===B.call(a)},I=RegExp.prototype.test,z=/\S/,T={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},qa=/\s*/,la=/\s+/,X=/\s*=/,Y=/\s*\}/,da=/#|\^|\/|>|\{|&|=|!/;u.prototype.eos=function ca(){return""===this.tail};u.prototype.scan=function va(a){a=this.tail.match(a);if(!a||0!==a.index)return"";a=a[0];this.tail=this.tail.substring(a.length);
this.pos+=a.length;return a};u.prototype.scanUntil=function Z(a){a=this.tail.search(a);var c;switch(a){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=c.length;return c};x.prototype.push=function ra(a){return new x(a,this)};x.prototype.lookup=function sa(a){var d=this.cache,e;if(d.hasOwnProperty(a))e=d[a];else{for(var f=this,g,h,k=!1;f;){if(0<a.indexOf("."))for(e=f.view,g=a.split("."),h=0;null!=e&&h<g.length;){if(!p(e,
g[h])){e=null;break}h===g.length-1&&(k=!0);e=e[g[h++]]}else p(f.view,a)?(e=f.view[a],k=!0):e=null;if(k)break;f=f.parent}d[a]=e}c(e)&&(e=e.call(this.view));return e};t.prototype.clearCache=function O(){this.cache={}};t.prototype.parse=function(a,c){var d=this.cache,e=d[a];null==e&&(e=d[a]=h(a,c));return e};t.prototype.render=function aa(a,c,d){var e=this.parse(a);c=c instanceof x?c:new x(c);return this.renderTokens(e,c,d,a)};t.prototype.renderTokens=function P(a,c,d,e){for(var f="",g,h,k,l=0,q=a.length;l<
q;++l)k=void 0,g=a[l],h=g[0],"#"===h?k=this.renderSection(g,c,d,e):"^"===h?k=this.renderInverted(g,c,d,e):">"===h?k=this.renderPartial(g,c,d,e):"&"===h?k=this.unescapedValue(g,c):"name"===h?k=this.escapedValue(g,c):"text"===h&&(k=this.rawValue(g)),void 0!==k&&(f+=k);return f};t.prototype.renderSection=function L(a,d,e,f){function g(a){return h.render(a,d,e)}var h=this,k="",l=d.lookup(a[1]);if(l){if(r(l))for(var q=0,p=l.length;q<p;++q)k+=this.renderTokens(a[4],d.push(l[q]),e,f);else if("object"===
typeof l||"string"===typeof l||"number"===typeof l)k+=this.renderTokens(a[4],d.push(l),e,f);else if(c(l)){if("string"!==typeof f)throw Error("Cannot use higher-order sections without the original template");l=l.call(d.view,f.slice(a[3],a[5]),g);null!=l&&(k+=l)}else k+=this.renderTokens(a[4],d,e,f);return k}};t.prototype.renderInverted=function U(a,c,d,e){var f=c.lookup(a[1]);if(!f||r(f)&&0===f.length)return this.renderTokens(a[4],c,d,e)};t.prototype.renderPartial=function l(a,d,e){if(e&&(a=c(e)?e(a[1]):
e[a[1]],null!=a))return this.renderTokens(this.parse(a),d,e,a)};t.prototype.unescapedValue=function q(c,d){c=d.lookup(c[1]);if(null!=c)return a.sanitizeUnescaped?a.sanitizeUnescaped(c):c};t.prototype.escapedValue=function D(c,d){c=d.lookup(c[1]);if(null!=c)return a.escape(c)};t.prototype.rawValue=function G(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var R=new t;a.clearCache=function(){return R.clearCache()};a.parse=function(a,c){return R.parse(a,c)};a.render=function(a,
c,d){if("string"!==typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+f(a)+'" was given as the first argument for mustache#render(template, view, partials)');return R.render(a,c,d)};a.to_html=function Q(d,e,f,g){var h=a.render(d,e,f);if(c(g))g(h);else return h};a.escape=g;a.sanitizeUnescaped=null;a.setUnescapedSanitizier=function J(c){a.sanitizeUnescaped=c};a.Scanner=u;a.Context=x;a.Writer=t});Ra.setUnescapedSanitizier(function(b){return Aa.sanitizeWithPolicy(b,function(a){return Da.includes(a)?{tagName:a,attribs:[]}:null})});function Sa(b){AMP.BaseTemplate.apply(this,arguments)}ea(Sa,AMP.BaseTemplate);Sa.prototype.compileCallback=function(){this.A=this.element.innerHTML;Ra.parse(this.A)};Sa.prototype.render=function(b){b=Ra.render(this.A,b);var a=Ma(b);b=this.win.document.createElement("div");b.innerHTML=a;return this.unwrap(b)};AMP.registerTemplate("amp-mustache",Sa);
})});
//# sourceMappingURL=amp-mustache-0.1.js.map
