(self.AMP=self.AMP||[]).push({n:"amp-youtube",v:"1496670637476",f:(function(AMP){var k;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a})(this);function n(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};var p=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=p.exec(a);){var d=decodeURIComponent(c[1]).trim(),f=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=f}return b};var r="";function t(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=q(c.location.originalHash||c.location.hash),f=q(c.location.search);r||(r=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011496670637476");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),filter:d.filter,minified:!0,lite:void 0!=f.amp_lite,test:!1,log:d.log,version:"1496670637476",rtvVersion:r}}c=b.AMP_MODE=c}return c};var u=Object.prototype.toString;Date.now();self.log=self.log||{user:null,dev:null};var v=self.log;function w(){if(v.user)return v.user;throw Error("failed to call initLogConstructor");};function x(a,b){a=a.__AMP_TOP||a;return y(a,b)}function z(a){var b=A,c=B(a),d=C(c);a=d;var f=D(a),e=f["video-manager"];e||(e=f["video-manager"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=b,e.context=c,e.resolve&&y(a,"video-manager"))}function E(a,b){a=B(a);a=C(a);return y(a,b)}function B(a){return a.nodeType?x((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function C(a){a=B(a);return a.isSingleDoc()?a.win:a}
function y(a,b){var c=D(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function D(a){var b=a.services;b||(b=a.services={});return b};function F(a){a.parentElement&&a.parentElement.removeChild(a)}function G(a){var b,c,d=b||function(a){return a},f=a.dataset;a=Object.create(null);var e=c?c:/^param(.+)/,g;for(g in f){var h=g.match(e);if(h){var l=h[1][0].toLowerCase()+h[1].substr(1);a[d(l)]=f[g]}}return a};var H,I="Webkit webkit Moz moz ms O o".split(" ");function K(a,b){for(var c in b){var d=a,f=b[c],e;e=d.style;var g=c;H||(H=Object.create(null));var h=H[g];if(!h){h=g;if(void 0===e[g]){var l;l=g;l=l.charAt(0).toUpperCase()+l.slice(1);a:{for(var m=0;m<I.length;m++){var J=I[m]+l;if(void 0!==e[J]){l=J;break a}}l=""}void 0!==e[l]&&(h=l)}H[g]=h}(e=h)&&(d.style[e]=f)}};function L(a,b,c){function d(a){try{return g(a)}catch(m){throw self.reportError(m),m;}}var f=void 0,e=a,g=c,h=f||!1;e.addEventListener(b,d,h);return function(){e&&e.removeEventListener(b,d,h);d=e=g=null}};function M(a,b,c){return L(a,b,c)}function N(a,b){var c=b,d=L(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function O(a){var b,c,d=new Promise(function(b){c=N(a,b)});d.then(c,c);b&&b(c);return d};function A(a){this.b=a;this.f=null;this.B=!1}A.prototype.register=function(a){var b=a;b.registerAction("play",b.play.bind(b,!1));b.registerAction("pause",b.pause.bind(b));b.registerAction("mute",b.mute.bind(b));b.registerAction("unmute",b.unmute.bind(b));if(a.element.hasAttribute("autoplay")&&a.supportsPlatform()){this.f=this.f||[];var c=new P(this.b,a);Q(this,c);this.f.push(c)}};
function Q(a,b){M(b.video.element,"amp:video:visibility",function(){b.updateVisibility()});M(b.video.element,"reloaded",function(){b.updateVisibility();b.j=!0;b.c&&b.i&&R(b)});if(!a.B){var c=function(){for(var b=0;b<a.f.length;b++)a.f[b].updateVisibility()},d=E(a.b,"viewport");d.onScroll(c);d.onChanged(c);a.B=!0}}
function P(a,b){var c=this;this.b=a;this.video=b;this.F=null;this.C=this.c=this.j=!1;this.w=x(a.win,"vsync");this.A=S.bind(null,a.win,t(a.win).lite);a=b.element;this.i=a.hasAttribute("autoplay");O(a).then(function(){c.updateVisibility();c.j=!0;c.c&&c.i&&R(c)});this.updateVisibility();this.i&&T(this)}function T(a){a.video.isInteractive()&&a.video.hideControls();a.A().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&U(a))})}
function U(a){function b(b){a.w.mutate(function(){d.classList.toggle("amp-video-eq-play",b)})}function c(){this.C=!0;this.video.showControls();this.video.unmute();e();g();h();d.remove();f.remove()}a.video.hideControls();var d=aa(a),f=ba(a);a.w.mutate(function(){a.video.element.appendChild(d);a.video.element.appendChild(f)});var e=M(f,"click",c.bind(a)),g=M(a.video.element,"pause",b.bind(a,!1)),h=M(a.video.element,"play",b.bind(a,!0))}
function R(a){!a.C&&E(a.b,"viewer").isVisible()&&a.A().then(function(b){b&&(a.c?a.video.play(!0):a.video.pause())})}
function aa(a){var b=a.b.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var f=b.createElement("div");f.classList.add("amp-video-eq-col");for(var e=1;2>=e;e++){var g=b.createElement("div");g.classList.add("amp-video-eq-"+d+"-"+e);f.appendChild(g)}c.appendChild(f)}var h=x(a.b.win,"platform");h.isIos()&&c.setAttribute("unpausable","");return c}
function ba(a){a=a.b.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}P.prototype.updateVisibility=function(){function a(){c.c!=d&&c.j&&c.i&&R(c)}function b(){if(c.video.isInViewport()){var a=c.video.element.getIntersectionChangeEntry(),b=a.intersectionRatio,d="number"===typeof b&&isFinite(b)?100*a.intersectionRatio:0;c.c=75<=d}else c.c=!1}var c=this,d=this.c;this.w.run({measure:b,mutate:a})};var V=null;
function S(a,b){if(V)return V;if(b)return V=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");K(c,{position:"fixed",top:"0",width:"0",height:"0",opacity:"0"});try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(f){}return V=Promise.resolve(!c.paused)};function W(a){AMP.BaseElement.call(this,a);this.g=0;this.h=null;this.l=!1;this.s=this.o=this.m=this.u=this.a=null}n(W,AMP.BaseElement);k=W.prototype;k.preconnectCallback=function(a){this.preconnect.url(X(this));this.preconnect.url("https://s.ytimg.com",a);this.preconnect.url("https://i.ytimg.com",a)};k.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};k.renderOutsideViewport=function(){return.75};
k.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};k.buildCallback=function(){var a=this;this.h=Y(this);this.m=new Promise(function(b){a.o=b});this.getPlaceholder()||ca(this);z(this.element);E(this.element,"video-manager").register(this)};
function X(a){if(a.u)return a.u;var b="https://www.youtube.com/embed/"+encodeURIComponent(a.h||"")+"?enablejsapi=1",c=G(a.element);"autoplay"in c&&(delete c.autoplay,w().error("AMP-YOUTUBE","Use autoplay attribute instead of data-param-autoplay"));"playsinline"in c||(c.playsinline="1");var d=a.element.hasAttribute("autoplay");d&&("iv_load_policy"in c||(c.iv_load_policy="3"),c.playsinline="1");var f=[],e;for(e in c){var g=c[e];if(null!=g)if(Array.isArray(g))for(var h=0;h<g.length;h++){var l=g[h];f.push(encodeURIComponent(e)+
"="+encodeURIComponent(l))}else f.push(encodeURIComponent(e)+"="+encodeURIComponent(g))}if(c=f.join("&"))b=b.split("#",2),e=b[0].split("?",2),c=e[0]+(e[1]?"?"+e[1]+"&"+c:"?"+c),b=c+=b[1]?"#"+b[1]:"";return a.u=b}
k.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe"),c=X(this);b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src=c;this.applyFillContent(b);this.a=b;this.s=M(this.win,"message",this.D.bind(this));this.element.appendChild(this.a);var d=this.loadPromise(this.a).then(function(){a.a.contentWindow.postMessage(JSON.stringify({event:"listening"}),"*");a.element.dispatchCustomEvent("load")});this.o(d);return d};
k.unlayoutCallback=function(){var a=this;this.a&&(F(this.a),this.a=null);this.s&&this.s();this.g=2;this.m=new Promise(function(b){a.o=b});return!0};k.pauseCallback=function(){this.a&&this.a.contentWindow&&1==this.g&&this.pause()};k.mutatedAttributesCallback=function(a){void 0!==a["data-videoid"]&&(this.h=Y(this),this.a&&Z(this,"loadVideoById",[this.h]))};
function Y(a){return w().assert(a.element.getAttribute("data-videoid"),"The data-videoid attribute is required for <amp-youtube> %s",a.element)}function Z(a,b,c){a.m.then(function(){if(a.a&&a.a.contentWindow){var d=JSON.stringify({event:"command",func:b,args:c||""});a.a.contentWindow.postMessage(d,"*")}})}
k.D=function(a){var b;(b="https://www.youtube.com"==a.origin&&a.source==this.a.contentWindow)&&(b=a.data)&&!(b="[object Object]"===u.call(a.data))&&(b=a.data,b=1>b.length?!1:0==b.lastIndexOf("{",0));if(b){var c;if("[object Object]"===u.call(a.data))c=a.data;else a:{try{c=JSON.parse(a.data);break a}catch(d){}c=void 0}a=c;void 0!==a&&("infoDelivery"==a.event&&a.info&&void 0!==a.info.playerState?(this.g=a.info.playerState,2==this.g?this.element.dispatchCustomEvent("pause"):1==this.g&&this.element.dispatchCustomEvent("play")):
"infoDelivery"==a.event&&a.info&&void 0!==a.info.muted&&this.l!=a.info.muted&&(this.l=a.info.muted,this.element.dispatchCustomEvent(this.l?"muted":"unmuted")))}};
function ca(a){var b=a.element.ownerDocument.createElement("img"),c=a.h||"";K(b,{"object-fit":"cover",visibility:"hidden"});b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+"/sddefault.jpg#404_is_fine";b.setAttribute("placeholder","");b.setAttribute("referrerpolicy","origin");a.applyFillContent(b);a.element.appendChild(b);a.loadPromise(b).then(function(){if(120==b.naturalWidth&&90==b.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+
"/hqdefault.jpg";return a.loadPromise(b)}).then(function(){K(b,{visibility:""})})}k.supportsPlatform=function(){return!0};k.isInteractive=function(){return!0};k.play=function(){Z(this,"playVideo")};k.pause=function(){Z(this,"pauseVideo")};k.mute=function(){Z(this,"mute")};k.unmute=function(){Z(this,"unMute")};k.showControls=function(){};k.hideControls=function(){};AMP.registerElement("amp-youtube",W);
})});
//# sourceMappingURL=amp-youtube-0.1.js.map
